### ISSUE TITLE
Wrong location name for us/cambridge-ma/02139

### ISSUE THREAD

**Issue by Sadi58** [RingOV/gis-weather#11]
I have this web page "http://www.accuweather.com/en/us/cambridge-ma/02139/weather-forecast/329319" showing title "Cambridge Weather - AccuWeather Forecast for MA 02139" but it's displayed in GIS-Weather as "Howick".
I even suspect that it is not just displaying a wrong name but the weather forecast is actually for another location which is 1 day ahead (e.g. somewhere in Australia?)
![gis-weather-cambridge-howick](https://cloud.githubusercontent.com/assets/6375934/6984059/ab8bade6-da2d-11e4-967f-5600d7b43d27.png)

**Comment by RingOV** [comment]
Try us/cambridge-ma/02139,329319
https://github.com/RingOV/gis-weather/wiki/How-to:-AccuWeather-city-code

**Comment by Sadi58** [comment]
That's it! Thanks a lot :-)

**Comment by JasonB42** [comment]
I have submitted pull request #13 to help make this obvious for places where two different numbers are needed.
