### ISSUE TITLE
Wind units: Beaufort scale

### ISSUE THREAD

**Issue by cascaval** [RingOV/gis-weather#12]
It would be great if Beaufort scale was added to wind units. I think that many people living close to a sea would appreciate this.

**Comment by RingOV** [comment]
If I have 4 Beaufort number. How to better display this?
4 B
4 N (number)
4 n
4 Bn
	
Maybe there are special characters?

**Comment by cascaval** [comment]
Are you asking what is the proper symbol for this unit? That would be a good question and I don't have 100% sure answer. Beaufort is an empirical measurement and is probably not as standardized as SI units.

[Wikipedia](https://en.wikipedia.org/wiki/Beaufort_scale) seems to be using "B" as the symbol ("4 B") but on lots of sites like [Windfinder](http://www.windfinder.com) they use "bft" as the symbol. So **I'd say "4 Bft" or lowercase "4 bft"**.

**Comment by RingOV** [comment]
880ba0a1ec115565e1766e453fcc1bb185dfe3ee

**Comment by cascaval** [comment]
Excellent. Thank you!
