### ISSUE TITLE
Display of pressure in inHG

### ISSUE THREAD

**Issue by Fredo-p** [RingOV/gis-weather#14]
Is is possible to change the unit display for pressure? In the US, the system used is inches of Mercury (inHG) and is displayed in a 4 digit number, with a decimal in between the second and third number.

Using Accuweather as my data source, I only see 1 inHG. Is there any way to get it to display the way it's used across the US ( 29.93 in vs 1 inHG)?

Would it also be possible to include an arrow to show whether the pressure is rising or falling, as indicated by the website?
![gis-weather issue](https://cloud.githubusercontent.com/assets/5199706/10950888/74e5ff4e-82f7-11e5-9412-0817914c4eb0.jpg)

**Comment by RingOV** [comment]
Fixed https://github.com/RingOV/gis-weather/commit/e8824f7e22049c9dd794c6ed9dd62e26885f7a72#diff-2a3713946e94b22a851a2e0ad21ddfc1L277

**Comment by Fredo-p** [comment]
Amazing. That was quick. Thank you. How soon before it's pushed and the software updater sees the update?

**Comment by RingOV** [comment]
This month

**Comment by Fredo-p** [comment]
Awesome. Thanks.
