### ISSUE TITLE
weather not refreshing

### ISSUE THREAD

**Issue by gdfox** [RingOV/gis-weather#15]
The weather is set to update every 30 minutes, but it is not. I have to manually refresh it.

**Comment by RingOV** [comment]
Hello,

1. Setup update to 1 min
2. Close widget
3. Run widget in terminal
4. Wait several min
5. Show output

**Comment by gdfox** [comment]
Thanks...

Here is the output:

Gis Weather 0.8.0
Configuration folder:
    /home/gfox/.config/gis-weather/gw_config1.json
Widget size:
    width = 684 height = 320 including indent = 20
Your screen supports alpha
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:22
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:23
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:24
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:25
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:26
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:27
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:28
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:29
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:31
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------
> Getting weather for 7 days
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/current-weather/2099212
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/month/2099212?view=table
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=2
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/overnight-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/morning-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/afternoon-weather-forecast/2099212?day=1
OK
> Downloading http://www.accuweather.com/en/us/coventry-ri/02816/evening-weather-forecast/2099212?day=1
OK
> weather received 17:32
> Next update in 1 min
----------------------------------------
> Check for new version (deb)
> You are using the latest version
----------------------------------------

**Comment by RingOV** [comment]
As you saw, automaticaly update working fine.
