### ISSUE TITLE
Gismeteo иконка

### ISSUE THREAD

**Issue by varlesh** [RingOV/gis-weather#17]
Появился новый статус "Снежные зёрна" - в большинстве тем вместо иконки NA.
Flat White:
![2016-02-11 18-12-20](https://cloud.githubusercontent.com/assets/8083855/12979972/4bc7c254-d0eb-11e5-96b1-9726712b1f55.png)
Default:
![2016-02-11 18-15-40](https://cloud.githubusercontent.com/assets/8083855/12980018/9099df98-d0eb-11e5-8fcd-00241ea50ca9.png)
Версия программы: 0.8.0

**Comment by RingOV** [comment]
Когда появится еще раз, нужно запустить через терминал и прислать как называется не найденная иконка. Заменю ее на иконку со снегом.

**Comment by varlesh** [comment]
[!] Не найдена иконка:
> /home/alex/.config/gis-weather/icons/flat_black/weather/d.mist.s2.svgz

**Comment by RingOV** [comment]
https://github.com/RingOV/gis-weather/commit/2f305218fdbfd6b9c8512fc5a94d59f1722c9ce3

**Comment by varlesh** [comment]
Спасибо :+1:
