### ISSUE TITLE
gis-weather doesn't start

### ISSUE THREAD

**Issue by zensubz** [RingOV/gis-weather#20]
Is there is a way to run gis-weather in Wheezy - I get the following lines in terminal:

Traceback (most recent call last):
  File "/usr/share/gis-weather/gis-weather.py", line 757, in expose
    weather1 = get_weather()
  File "/usr/share/gis-weather/gis-weather.py", line 413, in get_weather
    if app.show_edit_dialog():
  File "/usr/share/gis-weather/gis-weather.py", line 1506, in show_edit_dialog
    dialog, entrybox, treeview, bar_err, bar_ok, bar_label, combobox_weather_lang, weather_lang_list, combobox_service, grid_appid, entrybox_appid = city_id_dialog.create(self.window_main, APP_PATH, service);
  File "/usr/share/gis-weather/dialogs/city_id_dialog.py", line 109, in create
    ui.add_from_file(os.path.join(APP_PATH, "dialogs","city_id_dialog.ui"))
  File "/usr/lib/python3/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
gi._glib.GError: Unhandled tag: 'packing'
> Check for new version (gz)
Traceback (most recent call last):
  File "/usr/share/gis-weather/gis-weather.py", line 704, in redraw
    check_updates()
  File "/usr/share/gis-weather/gis-weather.py", line 462, in check_updates
    if diff_versions.diff(v.split('.'), new_ver):
  File "/usr/share/gis-weather/utils/diff_versions.py", line 7, in diff
    new_ver = fix_digits(new_ver)
  File "/usr/share/gis-weather/utils/diff_versions.py", line 21, in fix_digits
    if len(i) < 2:
TypeError: object of type 'int' has no len()

---
Python3 version: 3.2.3 and all dependencies have been installed. Thanks in advance.

**Comment by RingOV** [comment]
Show output
`gis-weather --version`
`dpkg -l | grep libgtk-3`

**Comment by zensubz** [comment]
gis-weather --version lists out (twice):

Gis Weather 0.8.0
Gis Weather 0.8.0

dpkg -l | grep libgtk-3 gives the following results:

ii  libgtk-3-0:i386             3.4.2-7+deb7u1               i386         GTK+ graphical user interface library
ii  libgtk-3-bin                  3.4.2-7+deb7u1               i386         programs for the GTK+ graphical user interface library
ii  libgtk-3-common         3.4.2-7+deb7u1               all          common files for the GTK+ graphical user interface library

Thanks. The same program works well in Ubuntu Trusty - so I hope it must be something to do with Gtk3/Glade.

**Comment by RingOV** [comment]
Try run gis-weather.py from old_gtk branch https://github.com/RingOV/gis-weather/archive/old_gtk.zip
Show all output

**Comment by zensubz** [comment]
Thanks. This is what I have got (for the old_gtk version):

`$ ./gis-weather.py 
Gis Weather 0.8.0.12
Configuration folder:
    /home/subz/.config/gis-weather/gw_config1.json
Widget size:
    width = 684 height = 320 including indent = 20
Your screen supports alpha
Traceback (most recent call last):
  File "./gis-weather.py", line 771, in expose
    weather1 = get_weather()
  File "./gis-weather.py", line 427, in get_weather
    if app.show_edit_dialog():
  File "./gis-weather.py", line 1525, in show_edit_dialog
    dialog, entrybox, treeview, bar_err, bar_ok, bar_label, combobox_weather_lang, weather_lang_list, combobox_service, grid_appid, entrybox_appid = city_id_dialog.create(self.window_main, APP_PATH, service);
  File "/home/subz/PDF/gis-weather-old_gtk/dialogs/city_id_dialog.py", line 109, in create
    ui.add_from_file(os.path.join(APP_PATH, "dialogs","city_id_dialog.ui"))
  File "/usr/lib/python3/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
gi._glib.GError: Unhandled tag: 'packing'
> Check for new version (gz)
> You are using the latest version
----------------------------------------
Traceback (most recent call last):
  File "./gis-weather.py", line 771, in expose
    weather1 = get_weather()
  File "./gis-weather.py", line 427, in get_weather
    if app.show_edit_dialog():
  File "./gis-weather.py", line 1525, in show_edit_dialog
    dialog, entrybox, treeview, bar_err, bar_ok, bar_label, combobox_weather_lang, weather_lang_list, combobox_service, grid_appid, entrybox_appid = city_id_dialog.create(self.window_main, APP_PATH, service);
  File "/home/subz/PDF/gis-weather-old_gtk/dialogs/city_id_dialog.py", line 109, in create
    ui.add_from_file(os.path.join(APP_PATH, "dialogs","city_id_dialog.ui"))
  File "/usr/lib/python3/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
gi._glib.GError: Unhandled tag: 'packing'
Traceback (most recent call last):
  File "./gis-weather.py", line 771, in expose
    weather1 = get_weather()
  File "./gis-weather.py", line 427, in get_weather
    if app.show_edit_dialog():
  File "./gis-weather.py", line 1525, in show_edit_dialog
    dialog, entrybox, treeview, bar_err, bar_ok, bar_label, combobox_weather_lang, weather_lang_list, combobox_service, grid_appid, entrybox_appid = city_id_dialog.create(self.window_main, APP_PATH, service);
  File "/home/subz/PDF/gis-weather-old_gtk/dialogs/city_id_dialog.py", line 109, in create
    ui.add_from_file(os.path.join(APP_PATH, "dialogs","city_id_dialog.ui"))
  File "/usr/lib/python3/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
gi._glib.GError: Unhandled tag: 'packing'
Traceback (most recent call last):
  File "./gis-weather.py", line 771, in expose
    weather1 = get_weather()
  File "./gis-weather.py", line 427, in get_weather
    if app.show_edit_dialog():
  File "./gis-weather.py", line 1525, in show_edit_dialog
    dialog, entrybox, treeview, bar_err, bar_ok, bar_label, combobox_weather_lang, weather_lang_list, combobox_service, grid_appid, entrybox_appid = city_id_dialog.create(self.window_main, APP_PATH, service);
  File "/home/subz/PDF/gis-weather-old_gtk/dialogs/city_id_dialog.py", line 109, in create
    ui.add_from_file(os.path.join(APP_PATH, "dialogs","city_id_dialog.ui"))
  File "/usr/lib/python3/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
gi._glib.GError: Unhandled tag: 'packing'
Traceback (most recent call last):
  File "./gis-weather.py", line 771, in expose
    weather1 = get_weather()
  File "./gis-weather.py", line 427, in get_weather
    if app.show_edit_dialog():
  File "./gis-weather.py", line 1525, in show_edit_dialog
    dialog, entrybox, treeview, bar_err, bar_ok, bar_label, combobox_weather_lang, weather_lang_list, combobox_service, grid_appid, entrybox_appid = city_id_dialog.create(self.window_main, APP_PATH, service);
  File "/home/subz/PDF/gis-weather-old_gtk/dialogs/city_id_dialog.py", line 109, in create
    ui.add_from_file(os.path.join(APP_PATH, "dialogs","city_id_dialog.ui"))
  File "/usr/lib/python3/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
gi._glib.GError: Unhandled tag: 'packing'
[1]    7475 terminated  ./gis-weather.py
`
I feel that the problem may be with python3-gi, and from the errors above it appears that glib available in Wheezy is creating some issues...?

**Comment by zensubz** [comment]
Forgot to mention this. I had to manually terminate gis-weather as it was just hanging around without giving anymore output. Hence that last line 'terminated ./gis-weather.py'.

**Comment by RingOV** [comment]
Problem was finded.
https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/998208

Try latest version of old_gtk
https://github.com/RingOV/gis-weather/archive/104c7f20282b648f72807e652ddf9d7f8a303941.zip

I removed some packin tags in GtkInfoBar https://github.com/RingOV/gis-weather/commit/104c7f20282b648f72807e652ddf9d7f8a303941
this is not fully solved problem. Then I open city_id_dialog.ui with Glade, all packing will auto recreated.

You can use this version and disable check of update option in preferences.
Or manually remove needed tag after other update.

**Comment by zensubz** [comment]
Partial success... This time the latest version you provided in the link could start, but it was not going beyond the initial city-selection/location screen. Waited and waited, and ultimately terminated the app. The terminal output is given below:

$ python3 gis-weather.py 
Gis Weather 0.8.0.12
Configuration folder:
    /home/subz/.config/gis-weather/gw_config1.json
Widget size:
    width = 684 height = 320 including indent = 20
Your screen supports alpha
[1]    6378 terminated  python3 gis-weather.py

I don't know if there was any fix for Glade in case of Debian Wheezy - there was a mention that the Ubuntu guys had brought out a fix for Glade in Precise (from the launchpad link you posted)...

Here is the link for screenshot: [http://imgur.com/BAQYs6v](url)

**Comment by RingOV** [comment]
Close this window and open from popup menu: Location→Setup. Or restart widget.
Then I tested on Weezy I saw clear city_id_dialog too.

**Comment by zensubz** [comment]
Thank you RingOV for all your efforts. This time I closed the city_id_dialog window as you had suggested, and then manually opened the Location-Setup from Widget. It opened but again after a few seconds another window popped up and just kept on hanging around, and if I close it again it would pop-up... I have attached the screenshot link. If this problem can't be fully solved for Wheezy then drop the whole issue - as this program is working in other versions of Debian/Ubuntu. I should not bother you too much for a problem that may be with my OS (which I am not able figure out)...

Here is the link for the screenshot: http://imgur.com/r3ZASi8

**Comment by RingOV** [comment]
Most easy way for You - is quikly close clear window, select gismeteo, type «1234» for city code and click «Add». After this program must be working right.

**Comment by zensubz** [comment]
Yes, finally it came to be alive..! Thanks for all your efforts. I tested three services, but didn't test OpenWeatherMap as it requires a signing in and I thought I could get the info from AccuWeather instead. The remaining two have some problem concerning downloading of weather-icons I guess... There was an endless loop with Gismeteo (I had to terminate the app ultimately), and also partially the same with Yr service. I have attached the screenshots so that you may look-in. From what I have seen AccuWeather is fine, so I am closing this. Thanks a lot for your kind inputs.

Links for screenshots: http://imgur.com/JhG5pNr (Gismeteo), http://imgur.com/V4102ig (Yr)
