### ISSUE TITLE
Night Time icons shown only

### ISSUE THREAD

**Issue by rosoau** [RingOV/gis-weather#39]
Hi
With the new version 0.8.3.4 on Ubuntu 16.04 Gnome-Flashback
Using Openweather.org
Only night time icons are shown regardless of time.
I'd rather have day time only icons so
I replaced all night icons with day ones in one of the themes
That is not very satisfactory though
Is there some tweak I can do in the code?
regards Rolf

**Comment by RingOV** [comment]
Hi,
> Is there some tweak I can do in the code?

You mean pull request?

**Comment by rosoau** [comment]
yes please make this a pull request.
From this end it may mean as little as replacing 
/usr/share/gis-weather/gis-weather.py
with the new version
I had a look at the differences of 0.8.2.5 and now with meld
but don't understand enough. Something to do with
choosing day or night icons according to our local time

**Comment by rosoau** [comment]
This screen-shot
![gis-weather py_001](https://user-images.githubusercontent.com/13397926/59715494-53f6bd00-9257-11e9-9e82-b0ebf180312e.png)
 is at 6 AM still night here in NSW Australia
All icons are night icons (V-Cloud [my compliments to the artist!])
I'll post the next image during the day

**Comment by rosoau** [comment]
Now it is daytime here 9 AM and we see a mixup in the "Today" block:
night = +10    day = 0 
this cannot be right
There is only one daytime icon for night and all the rest is still night
![gis-weather py_002](https://user-images.githubusercontent.com/13397926/59724570-b78be500-926d-11e9-8ead-7d73768d9398.png)

**Comment by RingOV** [comment]
I try Rylstone and saw same problem. May be problem in time zone. I try fix it.

**Comment by rosoau** [comment]
That would be good as it is the very best weather widget I know.
The mix up in the today block may be the difference between 
local and UTC time and the hardware clock versus system clock
I use local time for both; so system time is relevant

**Comment by RingOV** [comment]
Try 0.8.3.5. 
Fixed problem with time zone fcbde152109801788eb83f51e93b1eff92dc4384. Need testing.

**Comment by rosoau** [comment]
Thanks Developer. 
Today block now shows: Morning +2 Day + 7 and Evening - 1 which is proper
Evening has night icon; all others have day icons. which is proper
All forecasts have day icons. which is proper
Now-block still has night icon at 8 AM but shows the right temperature - 6
I'll check in a couple of hours if that icon changes to day icon and let you know

**Comment by rosoau** [comment]
OK well done !! 
Now 10:20 AM it shows a daytime icon in the now block;
and a good one on a freezing winter's morning
 
Thanks again.
regards Rolf
![gis-weather py_005](https://user-images.githubusercontent.com/13397926/59889189-8991d680-940e-11e9-81d3-aac0d0167f48.png)
