### ISSUE TITLE
Cannot download forecast

### ISSUE THREAD

**Issue by rosoau** [RingOV/gis-weather#44]
Downloading http://api.openweathermap.org/data/2.5/weather?id=2147714&lang=en&units=metric&appid=9559bbcc116ae1f545e982984609c2bc
1
OK

 Downloading http://api.openweathermap.org/data/2.5/forecast?id=2147714&lang=en&units=metric&appid=9559bbcc116ae1f545e982984609c2bc
Unable to download page, check the network connection

I believe my network connection is ok

The problem may be that they don't give away forecast data anymore
Other widgets, like screenlets, show the same error

Could somebody write a service script for weather.com
It seems the only forecast provider left providing forecast data

**Comment by RingOV** [comment]
try open url in browser

**Comment by rosoau** [comment]
I did open it in a browser and same there; only today's weather but no forecast. I'm on a satellite internet connection and who knows what sort of restrictions I have. I need to test this on a land line first.

**Comment by rosoau** [comment]
My apologies. The problem was my satellite internet connection. Ping is too long. Now I'm in the city with a mobile broadband modem and all works well; forecast and all! I have to say it again. This is by far the very best weather widget. I just tried so many of them and I'm so happy, now that gis-weather works, that I don't have to use any of them. Happy new year to you and to all the members.
