### ISSUE TITLE
Python 3.8 removed function

### ISSUE THREAD

**Issue by Dany-Dan** [RingOV/gis-weather#46]
Since Python 3.8 update, the "Block Additional info" is not working anymore and the log displays this error :
`if platform.dist()[0] == 'debian':
AttributeError: module 'platform' has no attribute 'dist'`

platform.dist() was deprecated and has been removed from Python 3.8.
To resolve the issue, I replaced it with :

```
import distro
if distro.linux_distribution()[0] == 'debian':
```

**Comment by RingOV** [comment]
ec0e15c8fdaf3b0e871406370df71b3d65d01224 Fixed

**Comment by Dany-Dan** [comment]
Thank you !
